//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osu.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osu.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort map.
        /// </summary>
        public static string Button_AbortMap {
            get {
                return ResourceManager.GetString("Button_AbortMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string Button_Ban {
            get {
                return ResourceManager.GetString("Button_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned by Blue.
        /// </summary>
        public static string Button_Ban_Blue {
            get {
                return ResourceManager.GetString("Button_Ban_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned by Red.
        /// </summary>
        public static string Button_Ban_Red {
            get {
                return ResourceManager.GetString("Button_Ban_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban recap.
        /// </summary>
        public static string Button_BanRecap {
            get {
                return ResourceManager.GetString("Button_BanRecap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Ranking Type.
        /// </summary>
        public static string Button_ChangeRankingType {
            get {
                return ResourceManager.GetString("Button_ChangeRankingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the room.
        /// </summary>
        public static string Button_CloseRoom {
            get {
                return ResourceManager.GetString("Button_CloseRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite players.
        /// </summary>
        public static string Button_InvitePlayers {
            get {
                return ResourceManager.GetString("Button_InvitePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Button_Manual {
            get {
                return ResourceManager.GetString("Button_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick recap.
        /// </summary>
        public static string Button_PickRecap {
            get {
                return ResourceManager.GetString("Button_PickRecap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert score.
        /// </summary>
        public static string Button_RevertScore {
            get {
                return ResourceManager.GetString("Button_RevertScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string Button_SetPassword {
            get {
                return ResourceManager.GetString("Button_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Button_Settings {
            get {
                return ResourceManager.GetString("Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game (5s).
        /// </summary>
        public static string Button_StartGame {
            get {
                return ResourceManager.GetString("Button_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch server.
        /// </summary>
        public static string Button_SwitchServer {
            get {
                return ResourceManager.GetString("Button_SwitchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unban.
        /// </summary>
        public static string Button_Unban {
            get {
                return ResourceManager.GetString("Button_Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm-up.
        /// </summary>
        public static string Button_Warmup {
            get {
                return ResourceManager.GetString("Button_Warmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome String.
        /// </summary>
        public static string Button_WelcomeString {
            get {
                return ResourceManager.GetString("Button_WelcomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string ChatView_Commands {
            get {
                return ResourceManager.GetString("ChatView_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;US&quot;: &quot;United States&quot;,
        ///    &quot;IN&quot;: &quot;India&quot;,
        ///    &quot;AF&quot;: &quot;Afghanistan&quot;,
        ///    &quot;AL&quot;: &quot;Albania&quot;,
        ///    &quot;DZ&quot;: &quot;Algeria&quot;,
        ///    &quot;AS&quot;: &quot;American Samoa&quot;,
        ///    &quot;AD&quot;: &quot;Andorra&quot;,
        ///    &quot;AO&quot;: &quot;Angola&quot;,
        ///    &quot;AI&quot;: &quot;Anguilla&quot;,
        ///    &quot;AQ&quot;: &quot;Antarctica&quot;,
        ///    &quot;AG&quot;: &quot;Antigua And Barbuda&quot;,
        ///    &quot;AR&quot;: &quot;Argentina&quot;,
        ///    &quot;AM&quot;: &quot;Armenia&quot;,
        ///    &quot;AW&quot;: &quot;Aruba&quot;,
        ///    &quot;AU&quot;: &quot;Australia&quot;,
        ///    &quot;AT&quot;: &quot;Austria&quot;,
        ///    &quot;AZ&quot;: &quot;Azerbaijan&quot;,
        ///    &quot;BS&quot;: &quot;Bahamas, The&quot;,
        ///    &quot;BH&quot;: &quot;Bahrain&quot;,
        ///    &quot;BD&quot;: &quot;Bangladesh&quot;,
        ///    &quot;BB&quot;: &quot;Barbados&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woah! So cool! :smirk:.
        /// </summary>
        public static string Discord_Footer {
            get {
                return ResourceManager.GetString("Discord_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can join the match on IRC by typing ```/join #mp_{0}```.
        /// </summary>
        public static string Discord_NewMatchDescription {
            get {
                return ResourceManager.GetString("Discord_NewMatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match has been created!.
        /// </summary>
        public static string Discord_NewMatchTitle {
            get {
                return ResourceManager.GetString("Discord_NewMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort taken in consideration!.
        /// </summary>
        public static string Error_Abort {
            get {
                return ResourceManager.GetString("Error_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The osu!api key is not valid!.
        /// </summary>
        public static string Error_ApiKeyInvalid {
            get {
                return ResourceManager.GetString("Error_ApiKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not connected to bancho!.
        /// </summary>
        public static string Error_BanchoDisconnect {
            get {
                return ResourceManager.GetString("Error_BanchoDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All bans have been selected or you can&apos;t ban a beatmap which is already banned!.
        /// </summary>
        public static string Error_BanLimit {
            get {
                return ResourceManager.GetString("Error_BanLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to ban the same number of maps for each team to display it!.
        /// </summary>
        public static string Error_BanSameNumber {
            get {
                return ResourceManager.GetString("Error_BanSameNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beatmap is already in this mappool!.
        /// </summary>
        public static string Error_BeatmapAlreadyInMappool {
            get {
                return ResourceManager.GetString("Error_BeatmapAlreadyInMappool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beatmap does not exist!.
        /// </summary>
        public static string Error_BeatmapIdNotFound {
            get {
                return ResourceManager.GetString("Error_BeatmapIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already in use.
        /// </summary>
        public static string Error_DuplicateName {
            get {
                return ResourceManager.GetString("Error_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is already in the list!.
        /// </summary>
        public static string Error_GameAlreadyExists {
            get {
                return ResourceManager.GetString("Error_GameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered id is not a valid number!.
        /// </summary>
        public static string Error_IdIsNotNumber {
            get {
                return ResourceManager.GetString("Error_IdIsNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not forget to set the acronym of your game before creating it!.
        /// </summary>
        public static string Error_MissingAcronym {
            get {
                return ResourceManager.GetString("Error_MissingAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not implemented yet!.
        /// </summary>
        public static string Error_NotImplemented {
            get {
                return ResourceManager.GetString("Error_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player already exists!.
        /// </summary>
        public static string Error_PlayerAlreadyInTeam {
            get {
                return ResourceManager.GetString("Error_PlayerAlreadyInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player does not exist!.
        /// </summary>
        public static string Error_PlayerNotFound {
            get {
                return ResourceManager.GetString("Error_PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room doesn&apos;t exist in the view model.
        /// </summary>
        public static string Error_RoomDoesNotExist {
            get {
                return ResourceManager.GetString("Error_RoomDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room has no played games!.
        /// </summary>
        public static string Error_RoomHasNoGames {
            get {
                return ResourceManager.GetString("Error_RoomHasNoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room has no players!.
        /// </summary>
        public static string Error_RoomHasNoPlayers {
            get {
                return ResourceManager.GetString("Error_RoomHasNoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use the same team twice!.
        /// </summary>
        public static string Error_SameTeam {
            get {
                return ResourceManager.GetString("Error_SameTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops!.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to unban the last banned map or ban a map first!.
        /// </summary>
        public static string Error_UnbanOrder {
            get {
                return ResourceManager.GetString("Error_UnbanOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to remove the last pick, not removing things randomly!.
        /// </summary>
        public static string Error_UnpickOrder {
            get {
                return ResourceManager.GetString("Error_UnpickOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a letter!.
        /// </summary>
        public static string Error_ValueNotLetter {
            get {
                return ResourceManager.GetString("Error_ValueNotLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close and try again later.
        /// </summary>
        public static string ErrorView_Close {
            get {
                return ResourceManager.GetString("ErrorView_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API is not answering :(.
        /// </summary>
        public static string ErrorView_Message {
            get {
                return ResourceManager.GetString("ErrorView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check osu!status twitter.
        /// </summary>
        public static string ErrorView_Status {
            get {
                return ResourceManager.GetString("ErrorView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mappool in the list or choose manual mode.
        /// </summary>
        public static string GamesView_SelectMappoolOrManual {
            get {
                return ResourceManager.GetString("GamesView_SelectMappoolOrManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And uncheck the games you wish to ignore.
        /// </summary>
        public static string GamesView_UncheckGames {
            get {
                return ResourceManager.GetString("GamesView_UncheckGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not found!.
        /// </summary>
        public static string GameView_MapNotFound {
            get {
                return ResourceManager.GetString("GameView_MapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string General_Password {
            get {
                return ResourceManager.GetString("General_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string General_Username {
            get {
                return ResourceManager.GetString("General_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free for all configuration.
        /// </summary>
        public static string HeadToHeadOptionsView_FreeForAllConfig {
            get {
                return ResourceManager.GetString("HeadToHeadOptionsView_FreeForAllConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player pick order.
        /// </summary>
        public static string HeadToHeadOptionsView_PlayerPickOrder {
            get {
                return ResourceManager.GetString("HeadToHeadOptionsView_PlayerPickOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking points.
        /// </summary>
        public static string HeadToHeadOptionsView_RankingPoints {
            get {
                return ResourceManager.GetString("HeadToHeadOptionsView_RankingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room configuration.
        /// </summary>
        public static string HeadToHeadOptionsView_RoomConfig {
            get {
                return ResourceManager.GetString("HeadToHeadOptionsView_RoomConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current player.
        /// </summary>
        public static string HeadToHeadRankingView_CurrentPlayer {
            get {
                return ResourceManager.GetString("HeadToHeadRankingView_CurrentPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next player.
        /// </summary>
        public static string HeadToHeadRankingView_NextPlayer {
            get {
                return ResourceManager.GetString("HeadToHeadRankingView_NextPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No map played yet.
        /// </summary>
        public static string HeadToHeadRankingView_NoMapPlayed {
            get {
                return ResourceManager.GetString("HeadToHeadRankingView_NoMapPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No order defined.
        /// </summary>
        public static string HeadToHeadRankingView_NoOrder {
            get {
                return ResourceManager.GetString("HeadToHeadRankingView_NoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string HeadToHeadRankingView_Player {
            get {
                return ResourceManager.GetString("HeadToHeadRankingView_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string HeadToHeadRankingView_PleaseWait {
            get {
                return ResourceManager.GetString("HeadToHeadRankingView_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string HeadToHeadRankingView_Score {
            get {
                return ResourceManager.GetString("HeadToHeadRankingView_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is RED, slots {2} to {3} --- {1} is BLUE, slots {4} to {5}.
        /// </summary>
        public static string Irc_SlotInfo {
            get {
                return ResourceManager.GetString("Irc_SlotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the players you wish to send messages to.
        /// </summary>
        public static string IrcView_SelectPlayers {
            get {
                return ResourceManager.GetString("IrcView_SelectPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappools.
        /// </summary>
        public static string MainView_Mappools {
            get {
                return ResourceManager.GetString("MainView_Mappools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainView_Options {
            get {
                return ResourceManager.GetString("MainView_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MainView_Overview {
            get {
                return ResourceManager.GetString("MainView_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string MainView_Rooms {
            get {
                return ResourceManager.GetString("MainView_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string MainView_Teams {
            get {
                return ResourceManager.GetString("MainView_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available, click to download..
        /// </summary>
        public static string MainView_UpdateAvailable {
            get {
                return ResourceManager.GetString("MainView_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map picker.
        /// </summary>
        public static string MappoolPickerView_MapPicker {
            get {
                return ResourceManager.GetString("MappoolPickerView_MapPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter beatmaps by Title or Artist.
        /// </summary>
        public static string MappoolPickerView_SearchWatermark {
            get {
                return ResourceManager.GetString("MappoolPickerView_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a mappool.
        /// </summary>
        public static string MappoolsView_AddMappool {
            get {
                return ResourceManager.GetString("MappoolsView_AddMappool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the mappool name.
        /// </summary>
        public static string MappoolsView_EnterMappoolName {
            get {
                return ResourceManager.GetString("MappoolsView_EnterMappoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a mappool.
        /// </summary>
        public static string MappoolsView_RenameMappool {
            get {
                return ResourceManager.GetString("MappoolsView_RenameMappool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a beatmap.
        /// </summary>
        public static string MappoolView_AddBeatmap {
            get {
                return ResourceManager.GetString("MappoolView_AddBeatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beatmap could not be deleted because the mappool is used in a room..
        /// </summary>
        public static string MappoolView_DeleteBeatmapErrorMappoolInUse {
            get {
                return ResourceManager.GetString("MappoolView_DeleteBeatmapErrorMappoolInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the beatmap?.
        /// </summary>
        public static string MappoolView_DeleteBeatmapMessage {
            get {
                return ResourceManager.GetString("MappoolView_DeleteBeatmapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete beatmap.
        /// </summary>
        public static string MappoolView_DeleteBeatmapTitle {
            get {
                return ResourceManager.GetString("MappoolView_DeleteBeatmapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the beatmap id (Must be a valid number). You can use &apos;;&apos; as a separator.
        /// </summary>
        public static string MappoolView_EnterBeatmapIdMessage {
            get {
                return ResourceManager.GetString("MappoolView_EnterBeatmapIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Beatmap.
        /// </summary>
        public static string MappoolView_EnterBeatmapIdTitle {
            get {
                return ResourceManager.GetString("MappoolView_EnterBeatmapIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the osu! room?.
        /// </summary>
        public static string MultiplayerCommandView_CloseRoomMessage {
            get {
                return ResourceManager.GetString("MultiplayerCommandView_CloseRoomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close room.
        /// </summary>
        public static string MultiplayerCommandView_CloseRoomTitle {
            get {
                return ResourceManager.GetString("MultiplayerCommandView_CloseRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new password for the room.
        /// </summary>
        public static string MultiplayerCommandView_NewPasswordMessage {
            get {
                return ResourceManager.GetString("MultiplayerCommandView_NewPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string MultiplayerCommandView_NewPasswordTitle {
            get {
                return ResourceManager.GetString("MultiplayerCommandView_NewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter usernames or userids separated by semicolons.
        /// </summary>
        public static string MultiplayerCommandView_PlayerNotFoundMessage {
            get {
                return ResourceManager.GetString("MultiplayerCommandView_PlayerNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        public static string MultiplayerCommandView_PlayerNotFoundTitle {
            get {
                return ResourceManager.GetString("MultiplayerCommandView_PlayerNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------ NEW MESSAGES ------------------.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin webhook (needed to enable the feature).
        /// </summary>
        public static string OptionsView_AdminWebhook {
            get {
                return ResourceManager.GetString("OptionsView_AdminWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to get your API key..
        /// </summary>
        public static string OptionsView_ApiHelp {
            get {
                return ResourceManager.GetString("OptionsView_ApiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu!api key (required).
        /// </summary>
        public static string OptionsView_ApiKey {
            get {
                return ResourceManager.GetString("OptionsView_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default BO when creating a new room.
        /// </summary>
        public static string OptionsView_BO {
            get {
                return ResourceManager.GetString("OptionsView_BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between messages (in ms).
        /// </summary>
        public static string OptionsView_Cooldown {
            get {
                return ResourceManager.GetString("OptionsView_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default GameMode for a new room.
        /// </summary>
        public static string OptionsView_GameMode {
            get {
                return ResourceManager.GetString("OptionsView_GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsView_General {
            get {
                return ResourceManager.GetString("OptionsView_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC.
        /// </summary>
        public static string OptionsView_IRC {
            get {
                return ResourceManager.GetString("OptionsView_IRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IRC password is different from your osu account password. Click here to get your IRC password..
        /// </summary>
        public static string OptionsView_IRCHelp {
            get {
                return ResourceManager.GetString("OptionsView_IRCHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Mappool for a new room.
        /// </summary>
        public static string OptionsView_Mappool {
            get {
                return ResourceManager.GetString("OptionsView_Mappool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can leave it blank if you want.
        /// </summary>
        public static string OptionsView_MappoolWatermark {
            get {
                return ResourceManager.GetString("OptionsView_MappoolWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp timer duration (0 = deactivated).
        /// </summary>
        public static string OptionsView_MpTimer {
            get {
                return ResourceManager.GetString("OptionsView_MpTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mp timer command is triggered after each map played.
        /// </summary>
        public static string OptionsView_MpTimerTooltip {
            get {
                return ResourceManager.GetString("OptionsView_MpTimerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public channel webhook.
        /// </summary>
        public static string OptionsView_PublicWebhook {
            get {
                return ResourceManager.GetString("OptionsView_PublicWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room options.
        /// </summary>
        public static string OptionsView_RoomOptions {
            get {
                return ResourceManager.GetString("OptionsView_RoomOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points for second ban (0 = deactivated).
        /// </summary>
        public static string OptionsView_SecondBanCount {
            get {
                return ResourceManager.GetString("OptionsView_SecondBanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string OvRoomView_Batch {
            get {
                return ResourceManager.GetString("OvRoomView_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string OvRoomView_Create {
            get {
                return ResourceManager.GetString("OvRoomView_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string OvRoomView_Link {
            get {
                return ResourceManager.GetString("OvRoomView_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next team to pick.
        /// </summary>
        public static string OvRoomView_NextTeamPick {
            get {
                return ResourceManager.GetString("OvRoomView_NextTeamPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string OvRoomView_Scores {
            get {
                return ResourceManager.GetString("OvRoomView_Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string OvRoomView_Winner {
            get {
                return ResourceManager.GetString("OvRoomView_Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acronym.
        /// </summary>
        public static string OvView_Acronym {
            get {
                return ResourceManager.GetString("OvView_Acronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins (addref).
        /// </summary>
        public static string OvView_Admins {
            get {
                return ResourceManager.GetString("OvView_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can leave it empty or add usernames separated by ;.
        /// </summary>
        public static string OvView_AdminsWatermark {
            get {
                return ResourceManager.GetString("OvView_AdminsWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select a batch letter to filter your matches.
        /// </summary>
        public static string OvView_BatchFilterWatermark {
            get {
                return ResourceManager.GetString("OvView_BatchFilterWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch letter.
        /// </summary>
        public static string OvView_BatchLetter {
            get {
                return ResourceManager.GetString("OvView_BatchLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Team.
        /// </summary>
        public static string OvView_BlueTeam {
            get {
                return ResourceManager.GetString("OvView_BlueTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a match.
        /// </summary>
        public static string OvView_CreateMatch {
            get {
                return ResourceManager.GetString("OvView_CreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the match in the overview.
        /// </summary>
        public static string OvView_CreateMatchInOverview {
            get {
                return ResourceManager.GetString("OvView_CreateMatchInOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default map id.
        /// </summary>
        public static string OvView_DefaultMapId {
            get {
                return ResourceManager.GetString("OvView_DefaultMapId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode.
        /// </summary>
        public static string OvView_GameMode {
            get {
                return ResourceManager.GetString("OvView_GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players per team.
        /// </summary>
        public static string OvView_PlayersPerTeam {
            get {
                return ResourceManager.GetString("OvView_PlayersPerTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a team....
        /// </summary>
        public static string OvView_PleaseSelectTeam {
            get {
                return ResourceManager.GetString("OvView_PleaseSelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Team.
        /// </summary>
        public static string OvView_RedTeam {
            get {
                return ResourceManager.GetString("OvView_RedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room configuration.
        /// </summary>
        public static string OvView_RoomConfiguration {
            get {
                return ResourceManager.GetString("OvView_RoomConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score mode.
        /// </summary>
        public static string OvView_ScoreMode {
            get {
                return ResourceManager.GetString("OvView_ScoreMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string OvView_Size {
            get {
                return ResourceManager.GetString("OvView_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team mode.
        /// </summary>
        public static string OvView_TeamMode {
            get {
                return ResourceManager.GetString("OvView_TeamMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message.
        /// </summary>
        public static string OvView_WelcomeMessage {
            get {
                return ResourceManager.GetString("OvView_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the player username.
        /// </summary>
        public static string PlayersView_AddPlayerMessage {
            get {
                return ResourceManager.GetString("PlayersView_AddPlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player.
        /// </summary>
        public static string PlayersView_AddPlayerTitle {
            get {
                return ResourceManager.GetString("PlayersView_AddPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck the players you wish to ignore.
        /// </summary>
        public static string PlayersView_Uncheck {
            get {
                return ResourceManager.GetString("PlayersView_Uncheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable notifications.
        /// </summary>
        public static string RoomOptionsView_EnableNotifications {
            get {
                return ResourceManager.GetString("RoomOptionsView_EnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp timer duration (0 = deactivated).
        /// </summary>
        public static string RoomOptionsView_MpTimer {
            get {
                return ResourceManager.GetString("RoomOptionsView_MpTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osu Mode selected for the maps.
        /// </summary>
        public static string RoomOptionsView_OsuMode {
            get {
                return ResourceManager.GetString("RoomOptionsView_OsuMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score mode.
        /// </summary>
        public static string RoomOptionsView_ScoreMode {
            get {
                return ResourceManager.GetString("RoomOptionsView_ScoreMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points for second ban (0 = deactivated).
        /// </summary>
        public static string RoomOptionsView_SecondBanCount {
            get {
                return ResourceManager.GetString("RoomOptionsView_SecondBanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string RoomOptionsView_Size {
            get {
                return ResourceManager.GetString("RoomOptionsView_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team mode.
        /// </summary>
        public static string RoomOptionsView_TeamMode {
            get {
                return ResourceManager.GetString("RoomOptionsView_TeamMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update room configuration.
        /// </summary>
        public static string RoomOptionsView_UpdateRoomConfig {
            get {
                return ResourceManager.GetString("RoomOptionsView_UpdateRoomConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the room ID.
        /// </summary>
        public static string RoomsView_AddRoomMessage {
            get {
                return ResourceManager.GetString("RoomsView_AddRoomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add room.
        /// </summary>
        public static string RoomsView_AddRoomTitle {
            get {
                return ResourceManager.GetString("RoomsView_AddRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Room.
        /// </summary>
        public static string RoomsView_CurrentRoom {
            get {
                return ResourceManager.GetString("RoomsView_CurrentRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the room?.
        /// </summary>
        public static string RoomsView_DeleteRoomMessage {
            get {
                return ResourceManager.GetString("RoomsView_DeleteRoomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete room.
        /// </summary>
        public static string RoomsView_DeleteRoomTitle {
            get {
                return ResourceManager.GetString("RoomsView_DeleteRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the room ranking type?.
        /// </summary>
        public static string RoomView_ChangeRankingMessage {
            get {
                return ResourceManager.GetString("RoomView_ChangeRankingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change room ranking type.
        /// </summary>
        public static string RoomView_ChangeRankingTitle {
            get {
                return ResourceManager.GetString("RoomView_ChangeRankingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string RoomView_Chat {
            get {
                return ResourceManager.GetString("RoomView_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string RoomView_Export {
            get {
                return ResourceManager.GetString("RoomView_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string RoomView_Games {
            get {
                return ResourceManager.GetString("RoomView_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC.
        /// </summary>
        public static string RoomView_IRC {
            get {
                return ResourceManager.GetString("RoomView_IRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string RoomView_Options {
            get {
                return ResourceManager.GetString("RoomView_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string RoomView_Players {
            get {
                return ResourceManager.GetString("RoomView_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string RoomView_Ranking {
            get {
                return ResourceManager.GetString("RoomView_Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has been successfully sent.
        /// </summary>
        public static string Success_MessageSent {
            get {
                return ResourceManager.GetString("Success_MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good!.
        /// </summary>
        public static string Success_Title {
            get {
                return ResourceManager.GetString("Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the team name.
        /// </summary>
        public static string TeamsView_AddTeamMessage {
            get {
                return ResourceManager.GetString("TeamsView_AddTeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a team.
        /// </summary>
        public static string TeamsView_AddTeamTitle {
            get {
                return ResourceManager.GetString("TeamsView_AddTeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a team or add a new one.
        /// </summary>
        public static string TeamsView_PleaseSelectTeam {
            get {
                return ResourceManager.GetString("TeamsView_PleaseSelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a team.
        /// </summary>
        public static string TeamsView_RenameTeamTitle {
            get {
                return ResourceManager.GetString("TeamsView_RenameTeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add team name as player.
        /// </summary>
        public static string TeamsView_TeamNameAsPlayer {
            get {
                return ResourceManager.GetString("TeamsView_TeamNameAsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add players.
        /// </summary>
        public static string TeamView_AddPlayers {
            get {
                return ResourceManager.GetString("TeamView_AddPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the players id or name. You can use &apos;;&apos; as a separator.
        /// </summary>
        public static string TeamView_AddPlayersMessage {
            get {
                return ResourceManager.GetString("TeamView_AddPlayersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player(s).
        /// </summary>
        public static string TeamView_AddPlayersTitle {
            get {
                return ResourceManager.GetString("TeamView_AddPlayersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string TeamVsOptionsView_Blue {
            get {
                return ResourceManager.GetString("TeamVsOptionsView_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO for the room.
        /// </summary>
        public static string TeamVsOptionsView_BO {
            get {
                return ResourceManager.GetString("TeamVsOptionsView_BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click refresh button after updating these options.
        /// </summary>
        public static string TeamVsOptionsView_ClickRefreshHint {
            get {
                return ResourceManager.GetString("TeamVsOptionsView_ClickRefreshHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to set this match as streamed? It will set OBS bans to this match and remove the one currently set..
        /// </summary>
        public static string TeamVsOptionsView_OBSMessage {
            get {
                return ResourceManager.GetString("TeamVsOptionsView_OBSMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS Mode.
        /// </summary>
        public static string TeamVsOptionsView_OBSTitle {
            get {
                return ResourceManager.GetString("TeamVsOptionsView_OBSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string TeamVsOptionsView_Red {
            get {
                return ResourceManager.GetString("TeamVsOptionsView_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First pick team.
        /// </summary>
        public static string TeamVsOptionsView_RollWinner {
            get {
                return ResourceManager.GetString("TeamVsOptionsView_RollWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Team.
        /// </summary>
        public static string TeamVsRankingView_NextTeam {
            get {
                return ResourceManager.GetString("TeamVsRankingView_NextTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team picking.
        /// </summary>
        public static string TeamVsRankingView_TeamPicking {
            get {
                return ResourceManager.GetString("TeamVsRankingView_TeamPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the download, make sure you are running the tool with administrator rights..
        /// </summary>
        public static string Update_NewVersionError {
            get {
                return ResourceManager.GetString("Update_NewVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download the latest version? The application will close..
        /// </summary>
        public static string Update_NewVersionMessage {
            get {
                return ResourceManager.GetString("Update_NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string Update_NewVersionTitle {
            get {
                return ResourceManager.GetString("Update_NewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the room....
        /// </summary>
        public static string Wait_CreatingRoom {
            get {
                return ResourceManager.GetString("Wait_CreatingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting the room....
        /// </summary>
        public static string Wait_Export {
            get {
                return ResourceManager.GetString("Wait_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to retrieve and register the player.
        /// </summary>
        public static string Wait_RetrievePlayer {
            get {
                return ResourceManager.GetString("Wait_RetrievePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving and creating the room....
        /// </summary>
        public static string Wait_RetrieveRoom {
            get {
                return ResourceManager.GetString("Wait_RetrieveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the message....
        /// </summary>
        public static string Wait_SendingMessage {
            get {
                return ResourceManager.GetString("Wait_SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string Wait_Title {
            get {
                return ResourceManager.GetString("Wait_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the room....
        /// </summary>
        public static string Wait_UpdatingRoom {
            get {
                return ResourceManager.GetString("Wait_UpdatingRoom", resourceCulture);
            }
        }
    }
}
