//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osu.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osu.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;US&quot;: &quot;United States&quot;,
        ///    &quot;IN&quot;: &quot;India&quot;,
        ///    &quot;AF&quot;: &quot;Afghanistan&quot;,
        ///    &quot;AL&quot;: &quot;Albania&quot;,
        ///    &quot;DZ&quot;: &quot;Algeria&quot;,
        ///    &quot;AS&quot;: &quot;American Samoa&quot;,
        ///    &quot;AD&quot;: &quot;Andorra&quot;,
        ///    &quot;AO&quot;: &quot;Angola&quot;,
        ///    &quot;AI&quot;: &quot;Anguilla&quot;,
        ///    &quot;AQ&quot;: &quot;Antarctica&quot;,
        ///    &quot;AG&quot;: &quot;Antigua And Barbuda&quot;,
        ///    &quot;AR&quot;: &quot;Argentina&quot;,
        ///    &quot;AM&quot;: &quot;Armenia&quot;,
        ///    &quot;AW&quot;: &quot;Aruba&quot;,
        ///    &quot;AU&quot;: &quot;Australia&quot;,
        ///    &quot;AT&quot;: &quot;Austria&quot;,
        ///    &quot;AZ&quot;: &quot;Azerbaijan&quot;,
        ///    &quot;BS&quot;: &quot;Bahamas, The&quot;,
        ///    &quot;BH&quot;: &quot;Bahrain&quot;,
        ///    &quot;BD&quot;: &quot;Bangladesh&quot;,
        ///    &quot;BB&quot;: &quot;Barbados&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
    }
}
