//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script_chan2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("script_chan2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ChatUserView_CloseButtonText {
            get {
                return ResourceManager.GetString("ChatUserView_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ChatView_MessageTextBoxHint {
            get {
                return ResourceManager.GetString("ChatView_MessageTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string ChatView_OpenNewButtonText {
            get {
                return ResourceManager.GetString("ChatView_OpenNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open new tab (Ctrl+T).
        /// </summary>
        public static string ChatView_OpenNewButtonTooltip {
            get {
                return ResourceManager.GetString("ChatView_OpenNewButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ChatView_SendButtonTooltip {
            get {
                return ResourceManager.GetString("ChatView_SendButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ColorListItemView_EditButtonTooltip {
            get {
                return ResourceManager.GetString("ColorListItemView_EditButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ColorsView_DefaultButtonText {
            get {
                return ResourceManager.GetString("ColorsView_DefaultButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DefaultColorValuesDialogView_CancelButtonText {
            get {
                return ResourceManager.GetString("DefaultColorValuesDialogView_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset all colors?.
        /// </summary>
        public static string DefaultColorValuesDialogView_LabelText {
            get {
                return ResourceManager.GetString("DefaultColorValuesDialogView_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string DefaultColorValuesDialogView_ResetButtonText {
            get {
                return ResourceManager.GetString("DefaultColorValuesDialogView_ResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditColorDialogView_CancelButtonText {
            get {
                return ResourceManager.GetString("EditColorDialogView_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditColorDialogView_SaveButtonText {
            get {
                return ResourceManager.GetString("EditColorDialogView_SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string MainView_ChatMenuItem {
            get {
                return ResourceManager.GetString("MainView_ChatMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string MainView_ColorsMenuItem {
            get {
                return ResourceManager.GetString("MainView_ColorsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string MainView_CommandsMenuItem {
            get {
                return ResourceManager.GetString("MainView_CommandsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MainView_ExportMenuItem {
            get {
                return ResourceManager.GetString("MainView_ExportMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappools.
        /// </summary>
        public static string MainView_MappoolsMenuItem {
            get {
                return ResourceManager.GetString("MainView_MappoolsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string MainView_MatchesMenuItem {
            get {
                return ResourceManager.GetString("MainView_MatchesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainView_SettingsMenuItem {
            get {
                return ResourceManager.GetString("MainView_SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string MainView_TeamsMenuItem {
            get {
                return ResourceManager.GetString("MainView_TeamsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        public static string MainView_TournamentsMenuItem {
            get {
                return ResourceManager.GetString("MainView_TournamentsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhooks.
        /// </summary>
        public static string MainView_WebhooksMenuItem {
            get {
                return ResourceManager.GetString("MainView_WebhooksMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewChatDialogView_CancelButtonText {
            get {
                return ResourceManager.GetString("NewChatDialogView_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string NewChatDialogView_OpenButtonText {
            get {
                return ResourceManager.GetString("NewChatDialogView_OpenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string NewChatDialogView_UserTextBoxHint {
            get {
                return ResourceManager.GetString("NewChatDialogView_UserTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string SettingsView_ApiKeyTextBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_ApiKeyTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancho Connected.
        /// </summary>
        public static string SettingsView_BanchoConnectedTooltip {
            get {
                return ResourceManager.GetString("SettingsView_BanchoConnectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancho Connecting.
        /// </summary>
        public static string SettingsView_BanchoConnectingTooltip {
            get {
                return ResourceManager.GetString("SettingsView_BanchoConnectingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancho Disconnected.
        /// </summary>
        public static string SettingsView_BanchoDisconnectedTooltip {
            get {
                return ResourceManager.GetString("SettingsView_BanchoDisconnectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string SettingsView_DiscardButtonText {
            get {
                return ResourceManager.GetString("SettingsView_DiscardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable notifications.
        /// </summary>
        public static string SettingsView_EnableNotificationsCheckBoxText {
            get {
                return ResourceManager.GetString("SettingsView_EnableNotificationsCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound when all players are ready or map has finished.
        /// </summary>
        public static string SettingsView_EnableNotificationsCheckBoxTooltip {
            get {
                return ResourceManager.GetString("SettingsView_EnableNotificationsCheckBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get API key.
        /// </summary>
        public static string SettingsView_GetApiKeyButtonText {
            get {
                return ResourceManager.GetString("SettingsView_GetApiKeyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IRC password.
        /// </summary>
        public static string SettingsView_GetIrcPasswordButtonText {
            get {
                return ResourceManager.GetString("SettingsView_GetIrcPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC Password.
        /// </summary>
        public static string SettingsView_IrcPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_IrcPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC Timeout.
        /// </summary>
        public static string SettingsView_IrcTimeoutTextBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_IrcTimeoutTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC Username.
        /// </summary>
        public static string SettingsView_IrcUsernameTextBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_IrcUsernameTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsView_LanguagesComboBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_LanguagesComboBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification sound file.
        /// </summary>
        public static string SettingsView_NotificationSoundFileTextBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_NotificationSoundFileTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty for default.
        /// </summary>
        public static string SettingsView_NotificationSoundFileTextBoxTooltip {
            get {
                return ResourceManager.GetString("SettingsView_NotificationSoundFileTextBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config file.
        /// </summary>
        public static string SettingsView_OpenConfigFileButtonText {
            get {
                return ResourceManager.GetString("SettingsView_OpenConfigFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Bancho Connected.
        /// </summary>
        public static string SettingsView_PrivateBanchoConnectedTooltip {
            get {
                return ResourceManager.GetString("SettingsView_PrivateBanchoConnectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Bancho Connecting.
        /// </summary>
        public static string SettingsView_PrivateBanchoConnectingTooltip {
            get {
                return ResourceManager.GetString("SettingsView_PrivateBanchoConnectingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Bancho Disconnected.
        /// </summary>
        public static string SettingsView_PrivateBanchoDisconnectedTooltip {
            get {
                return ResourceManager.GetString("SettingsView_PrivateBanchoDisconnectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsView_SaveButtonText {
            get {
                return ResourceManager.GetString("SettingsView_SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string SettingsView_SelectNotificationSoundFileButtonText {
            get {
                return ResourceManager.GetString("SettingsView_SelectNotificationSoundFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string SettingsView_TestApiKeyButtonText {
            get {
                return ResourceManager.GetString("SettingsView_TestApiKeyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer After Game Duration.
        /// </summary>
        public static string SettingsView_TimerAfterGameDurationTextBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_TimerAfterGameDurationTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer After Pick Duration.
        /// </summary>
        public static string SettingsView_TimerAfterPickDurationTextBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_TimerAfterPickDurationTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Command Duration.
        /// </summary>
        public static string SettingsView_TimerCommandDurationTextBoxHint {
            get {
                return ResourceManager.GetString("SettingsView_TimerCommandDurationTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use private bancho.
        /// </summary>
        public static string SettingsView_UsePrivateBanchoCheckBox {
            get {
                return ResourceManager.GetString("SettingsView_UsePrivateBanchoCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Window_CloseButtonTooltip {
            get {
                return ResourceManager.GetString("Window_CloseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Window_MaximizeButtonTooltip {
            get {
                return ResourceManager.GetString("Window_MaximizeButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Window_MinimizeButtonTooltip {
            get {
                return ResourceManager.GetString("Window_MinimizeButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Window_RestoreButtonTooltip {
            get {
                return ResourceManager.GetString("Window_RestoreButtonTooltip", resourceCulture);
            }
        }
    }
}
